spring.application.name=livreur
# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Livraison
spring.datasource.username=postgres
spring.datasource.password=melvin18
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
